// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskDbContext))]
    [Migration("20260924111436_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.BLOCK", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("PRISON_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.Property<int>("security_level")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PRISON_Id");

                    b.ToTable("BLOCK");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.BUILDING", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("PRISON_Id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("PRISON_Id");

                    b.ToTable("BUILDING");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CHAMBER", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("BLOCKid")
                        .HasColumnType("int");

                    b.Property<int?>("CHAMBERid")
                        .HasColumnType("int");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.Property<int>("maximum_capacity")
                        .HasColumnType("int");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("BLOCKid");

                    b.HasIndex("CHAMBERid");

                    b.ToTable("CHAMBER");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CRIME", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Difficulty_level")
                        .HasColumnType("int");

                    b.Property<int>("PRISONER_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("PRISONER_Id");

                    b.ToTable("CRIME");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.GUARDS", b =>
                {
                    b.Property<int>("GUARDS_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GUARDS_Id"));

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Prison_Id")
                        .HasColumnType("int");

                    b.Property<int>("Worker_number")
                        .HasColumnType("int");

                    b.Property<string>("job")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("GUARDS_Id");

                    b.HasIndex("Prison_Id");

                    b.ToTable("GUARDS");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PRISON", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Maximum_capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("PRISON");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PRISONERS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CHAMBER_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VISITORSid")
                        .HasColumnType("int");

                    b.Property<int>("VISIT_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("arrival_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("personal_number")
                        .HasColumnType("int");

                    b.Property<bool>("prisoner_status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("CHAMBER_Id");

                    b.HasIndex("VISITORSid");

                    b.HasIndex("VISIT_Id");

                    b.ToTable("PRISONERS");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PUNISHMENT", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("PRISONERS_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("punishment_Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("PRISONERS_Id");

                    b.ToTable("PUNISHMENT");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.SHIFT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("finish_time")
                        .HasColumnType("int");

                    b.Property<int>("start_time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SHIFT");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.VISIT", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("DATE")
                        .HasColumnType("date");

                    b.Property<int>("finish_time")
                        .HasColumnType("int");

                    b.Property<int>("start_time")
                        .HasColumnType("int");

                    b.Property<string>("visiting_status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("id");

                    b.ToTable("VISIT");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.VISITORS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Telephone_number")
                        .HasColumnType("int");

                    b.Property<int>("VISIT_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("personal_number")
                        .HasColumnType("int");

                    b.Property<string>("relation_to_the_prisoner")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("id");

                    b.HasIndex("VISIT_Id");

                    b.ToTable("VISITORS");
                });

            modelBuilder.Entity("GUARDSSHIFT", b =>
                {
                    b.Property<int>("GUARDS_Id")
                        .HasColumnType("int");

                    b.Property<int>("ShiftsId")
                        .HasColumnType("int");

                    b.HasKey("GUARDS_Id", "ShiftsId");

                    b.HasIndex("ShiftsId");

                    b.ToTable("GUARDSSHIFT");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.BLOCK", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.PRISON", "PRISON")
                        .WithMany("Blocks")
                        .HasForeignKey("PRISON_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRISON");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.BUILDING", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.PRISON", "PRISON")
                        .WithMany("Building")
                        .HasForeignKey("PRISON_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRISON");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CHAMBER", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.BLOCK", null)
                        .WithMany("Chambers")
                        .HasForeignKey("BLOCKid");

                    b.HasOne("DatabaseTask.Core.Domain.CHAMBER", null)
                        .WithMany("Chambers")
                        .HasForeignKey("CHAMBERid");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CRIME", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.PRISONERS", "PRISONERS")
                        .WithMany()
                        .HasForeignKey("PRISONER_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRISONERS");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.GUARDS", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.PRISON", "PRISON")
                        .WithMany("Guards")
                        .HasForeignKey("Prison_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRISON");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PRISONERS", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.CHAMBER", "CHAMBER")
                        .WithMany("Prisoners")
                        .HasForeignKey("CHAMBER_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.VISITORS", null)
                        .WithMany("Prisoners")
                        .HasForeignKey("VISITORSid");

                    b.HasOne("DatabaseTask.Core.Domain.VISIT", "VISIT")
                        .WithMany("Prisoners")
                        .HasForeignKey("VISIT_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CHAMBER");

                    b.Navigation("VISIT");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PUNISHMENT", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.PRISONERS", "PRISONERS")
                        .WithMany()
                        .HasForeignKey("PRISONERS_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PRISONERS");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.VISITORS", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.VISIT", "VISIT")
                        .WithMany("Visitors")
                        .HasForeignKey("VISIT_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VISIT");
                });

            modelBuilder.Entity("GUARDSSHIFT", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.GUARDS", null)
                        .WithMany()
                        .HasForeignKey("GUARDS_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseTask.Core.Domain.SHIFT", null)
                        .WithMany()
                        .HasForeignKey("ShiftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.BLOCK", b =>
                {
                    b.Navigation("Chambers");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.CHAMBER", b =>
                {
                    b.Navigation("Chambers");

                    b.Navigation("Prisoners");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.PRISON", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Building");

                    b.Navigation("Guards");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.VISIT", b =>
                {
                    b.Navigation("Prisoners");

                    b.Navigation("Visitors");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.VISITORS", b =>
                {
                    b.Navigation("Prisoners");
                });
#pragma warning restore 612, 618
        }
    }
}
